<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Branch_admin extends APP_Controller
{
    function __construct()
    {
        parent::__construct();
		if (!$this->ion_auth->logged_in()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        }
		else {
			if (!check_access($this->session->userdata('user_id'),'branch_admin')){
				redirect(get_default_page($this->session->userdata('user_id')), 'refresh');
			}
		}
        $this->load->model('Branch_admin_model');
    } 

    /*
     * Listing of branch_admins
     */
    function index()
    {
        $data['branch_admins'] = $this->Branch_admin_model->get_all_branch_admins_details();
		//echo $this->db->last_query();
        $this->_tpl('branch_admin/list',$data);
    }

    /*
     * Adding a new branch_admin
     */
    function add()
    {   
	    $data['branches'] = $this->Branch_model->get_all_branch();

		$this->form_validation->set_rules('password','Password','required|max_length[255]');
		$this->form_validation->set_rules('email','Email','required|max_length[100]|valid_email');
		$this->form_validation->set_rules('first_name','First Name','max_length[50]|required');
		$this->form_validation->set_rules('last_name','Last Name','max_length[50]|required');
		$this->form_validation->set_rules('branch_id','Branch','required');
		
		if($this->form_validation->run())     
        {  
            $email    = strtolower($this->input->post('email'));
            $identity = $email;
            $password = $this->input->post('password');

            $additional_data = array(
                'first_name' => $this->input->post('first_name'),
                'last_name'  => $this->input->post('last_name'),
                'company'    => $this->input->post('company'),
                'phone'      => $this->input->post('phone'),
            );
			$groups = array('2');
			$user_id = $this->Ion_auth_model->register($identity, $password, $email, $additional_data,$groups);
            
            $params = array(
				'branch_id' => $this->input->post('branch_id'),
				'user_id' => $user_id,
            );
			$branch_admin_id = $this->Branch_admin_model->add_branch_admin($params);
			/*$params = array();
			 foreach ($this->input->post('branch_id') as $selectedOption){
				$branch_admin_data = array(
				  'branch_id' => $selectedOption,
				  'user_id' => $user_id,
			   );
			   $params[] = $branch_admin_data;
			}  
            if(count($params)){
				 $branch_admin_id = $this->Branch_admin_model->add_branch_admin_in_batch($params);
				 echo $this->db->last_query();
			}*/
           
            redirect('branch_admin/index');
        }
        else
        {
            $this->_tpl('branch_admin/add',$data);
        }
    }  

    /*
     * Editing a branch_admin
     */
    function edit($id)
    {   
		$data['branches'] = $this->Branch_model->get_all_branch();
        // check if the branch_admin exists before trying to edit it
        $branch_admin = $this->Branch_admin_model->get_branch_admin($id);
        
		if(isset($branch_admin['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('email','Email','required|max_length[100]|valid_email');
			$this->form_validation->set_rules('first_name','First Name','max_length[50]|required');
			$this->form_validation->set_rules('last_name','Last Name','max_length[50]|required');
			$this->form_validation->set_rules('branch_id','Branch','required');
		
			if($this->form_validation->run())     
            {   
		
		
				$data = array(
					'first_name' => $this->input->post('first_name'),
					'last_name'  => $this->input->post('last_name'),
					'company'    => $this->input->post('company'),
					'phone'      => $this->input->post('phone'),
				);

				// update the password if it was posted
				if ($this->input->post('password'))
				{
					$data['password'] = $this->input->post('password');
				}
				
				$this->ion_auth->update($branch_admin['user_id'], $data);

				 $params = array(
					'branch_id' => $this->input->post('branch_id')
                );

                $this->Branch_admin_model->update_branch_admin($id,$params);
				redirect('branch_admin/index');
                          
			}
            else
            {   
		        $data['user'] = $this->User_model->get_user($branch_admin['user_id']);
                $data['branch_admin'] = $this->Branch_admin_model->get_branch_admin($id);
    
                $this->_tpl('branch_admin/edit',$data);
            }
        }
        else
            show_error('The branch_admin you are trying to edit does not exist.');
    } 

    /*
     * Deleting branch_admin
     */
    function remove($id)
    {
        $branch_admin = $this->Branch_admin_model->get_branch_admin($id);

        // check if the branch_admin exists before trying to delete it
        if(isset($branch_admin['id']))
        {
			$this->ion_auth->delete_user($branch_admin['user_id']);  
            $this->Branch_admin_model->delete_branch_admin($id);
            redirect('branch_admin/index');
        }
        else
            show_error('The branch_admin you are trying to delete does not exist.');
    }
    
}
