<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Courses_catalog extends APP_Controller
{
    function __construct()
    {
        parent::__construct();
		if (!$this->ion_auth->logged_in()) {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        }
		else {
			if (!check_access($this->session->userdata('user_id'),'courses_catalog')){
				redirect(get_default_page($this->session->userdata('user_id')), 'refresh');
			}
		}
        $this->load->model('Courses_catalog_model');
		$this->load->model('Category_model');
    } 

    /*
     * Listing of courses_catalog
     */
    function index()
    {
        $data['courses_catalog'] = $this->Courses_catalog_model->get_all_courses_catalog_details();
        $this->_tpl('courses_catalog/list',$data);
    }

    /*
     * Adding a new courses_catalog
     */
     function add()
    {   
		$data['categories'] = $this->Category_model->get_all_categories();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('category_id','Category Id','required');
		$this->form_validation->set_rules('course_code','Course Code','max_length[40]|required');
		$this->form_validation->set_rules('course_name','Course Name','max_length[200]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'category_id' => $this->input->post('category_id'),
				'course_code' => $this->input->post('course_code'),
				'course_name' => $this->input->post('course_name'),
				'course_summary' => $this->input->post('course_summary'),
				'course_contents' => $this->input->post('course_contents'),
				'notes' => $this->input->post('notes'),
            );
            
            $courses_catalog_id = $this->Courses_catalog_model->add_courses_catalog($params);
            redirect('courses_catalog/index');
        }
        else
        {
            $this->_tpl('courses_catalog/add',$data);
        }
    }  

    /*
     * Editing a courses_catalog
     */
    function edit($course_id)
    {   
	    $data['categories'] = $this->Category_model->get_all_categories();
        // check if the courses_catalog exists before trying to edit it
        $courses_catalog = $this->Courses_catalog_model->get_courses_catalog($course_id);
        
        if(isset($courses_catalog['course_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('category_id','Category Id','required');
			$this->form_validation->set_rules('course_code','Course Code','max_length[40]|required');
			$this->form_validation->set_rules('course_name','Course Name','max_length[200]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'category_id' => $this->input->post('category_id'),
					'course_code' => $this->input->post('course_code'),
					'course_name' => $this->input->post('course_name'),
					'course_summary' => $this->input->post('course_summary'),
					'course_contents' => $this->input->post('course_contents'),
					'notes' => $this->input->post('notes'),
                );

                $this->Courses_catalog_model->update_courses_catalog($course_id,$params);            
                redirect('courses_catalog/index');
            }
            else
            {   
                $data['courses_catalog'] = $this->Courses_catalog_model->get_courses_catalog($course_id);
    
                $this->_tpl('courses_catalog/edit',$data);
            }
        }
        else
            show_error('The courses_catalog you are trying to edit does not exist.');
    } 


    /*
     * Deleting courses_catalog
     */
    function remove($course_id)
    {
        $courses_catalog = $this->Courses_catalog_model->get_courses_catalog($course_id);

        // check if the courses_catalog exists before trying to delete it
        if(isset($courses_catalog['course_id']))
        {
            $this->Courses_catalog_model->delete_courses_catalog($course_id);
            redirect('courses_catalog/index');
        }
        else
            show_error('The courses_catalog you are trying to delete does not exist.');
    }
    
}
