<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category by category_id
     */
    function get_category($category_id)
    {
        return $this->db->get_where('categories',array('category_id'=>$category_id))->row_array();
    }
    
    /*
     * Get all categories
     */
    function get_all_categories()
    {
        return $this->db->get('categories')->result_array();
    }
    
    /*
     * function to add new category
     */
    function add_category($params)
    {
        $this->db->insert('categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category
     */
    function update_category($category_id,$params)
    {
        $this->db->where('category_id',$category_id);
        $this->db->update('categories',$params);
    }
    
    /*
     * function to delete category
     */
    function delete_category($category_id)
    {
        $this->db->delete('categories',array('category_id'=>$category_id));
    }
}
