<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Faculty_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faculty by id
     */
    function get_faculty($id)
    {
        return $this->db->get_where('faculty',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all faculty
     */
    function get_all_faculty()
    {
        return $this->db->get_where('faculty',array('active'=>'1'))->result_array();
    }
    
    /*
     * function to add new faculty
     */
    function add_faculty($params)
    {
        $this->db->insert('faculty',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update faculty
     */
    function update_faculty($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('faculty',$params);
    }
    
    /*
     * function to delete faculty
     */
    function delete_faculty($id)
    {
        //$this->db->delete('faculty',array('id'=>$id));
		$params = array(
					'active' => '0'
                );
		$this->db->where('id',$id);
        $this->db->update('faculty',$params);
    }
}
