<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Group_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get group by id
     */
    function get_group($id)
    {
        return $this->db->get_where('groups',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all groups
     */
    function get_all_groups()
    {
        return $this->db->get('groups')->result_array();
    }
    
    /*
     * function to add new group
     */
    function add_group($params)
    {
        $this->db->insert('groups',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update group
     */
    function update_group($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('groups',$params);
    }
    
    /*
     * function to delete group
     */
    function delete_group($id)
    {
        $this->db->delete('groups',array('id'=>$id));
    }
}
