<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get student by student_id
     */
    function get_student($student_id)
    {
        return $this->db->get_where('students',array('student_id'=>$student_id))->row_array();
    }
    
    /*
     * Get all students
     */
    function get_all_students_details()
    {
        $this->db->select('students.*,branch.*');
		$this->db->from('students');
		$this->db->join('branch', 'branch.id = students.branch_id');
		$this->db->where('students.active','1');
		return $this->db->get()->result_array();
    }
    
	/*
     * Get all students
     */
    function get_all_students()
    {
        return $this->db->get_where('students',array('active'=>'1'))->result_array();
    }
    
    /*
     * function to add new student
     */
    function add_student($params)
    {
        $this->db->insert('students',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update student
     */
    function update_student($student_id,$params)
    {
        $this->db->where('student_id',$student_id);
        $this->db->update('students',$params);
    }
    
    /*
     * function to delete student
     */
    function delete_student($student_id)
    {
        //$this->db->delete('students',array('student_id'=>$student_id));
		$params = array(
					'active' => '0'
                );
		$this->db->where('student_id',$student_id);
        $this->db->update('students',$params);
    }
}
