<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by id
     */
    function get_user($id)
    {
        return $this->db->get_where('users',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all users
     */
    function get_all_users()
    {
        return $this->db->get('users')->result_array();
    }
	
	/*
     * Get all users by group
     */
    function get_all_users_admin_by_group($group_id)
    {
		$user_ids = array('1');
		$this->db->select('u.*');
		$this->db->from('users u');
		$this->db->join('users_groups ug', 'ug.user_id = u.id'); // this joins the user table to users_groups
		$this->db->where('ug.group_id',$group_id);
		$this->db->where_not_in('ug.user_id', $user_ids);
        return $this->db->get()->result_array();
    }
    
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($id)
    {
        $this->db->delete('users',array('id'=>$id));
    }
}
